### ISSUE TITLE
Support Restore Settings During Service Creation

### ISSUE THREAD

**Issue by Kidswiss** [vshn/provider-exoscale#80]
### Summary

**As** User/VSHNeer
**I want** to be able to restore existing exoscale backups by self-service
**So that** I can restore databases without many manual steps

### Context

Currently it's not easy to restore backups into a proper AppCat service again. It needs a lot of steps, see https://github.com/vshn/application-catalog-docs/pull/51

This feature would make it much simpler to restore backups directly during the creation of a new dbaas service.

### Out of Scope

TBD

### Further links

1. DBaaS backup docs: https://community.exoscale.com/documentation/dbaas/lifecycle-management/#backups-and-restore
2. Redis Creation docs: https://openapi-v2.exoscale.com/operation/operation-create-dbaas-service-redis
3. PostgreSQL creation docs: https://openapi-v2.exoscale.com/operation/operation-create-dbaas-service-pg

### Acceptance Criteria

Claim Proposal:

```yaml
apiVersion: exoscale.appcat.vshn.io/v1
kind: Exoscale*
metadata:
  name: my-mysql-example
  namespace: my-namespace
spec:
  parameters:
    restore:
      from: #name of the exoscale service with the backup
      pointInTime: #iso timestamp of the backup, for services that support it
      backupName: # for services without PITR support.
```

* Security implications: it could allow users to potentially restore backups of other users. If they can guess the random name.
* The user can determine what backups they have available. Either:
  *  The point in time range they can specify
  *  Or the names of the available backups
* The claims and compositions pass-through the necessary parameters.
* Testing: 
  * Create an AppCat service instance, and try to restore it via a claim
* Documentation:
  * End-User docs how to perform the restores

### Implementation Ideas

TBD

### Notes

1. If no timestamp is provided for the restore time, Exoscale will just restore the most recent backup.
2. There are two kinds of backups on Exoscale, for services that support point and time and those that don't. They need different settings respectively.
